# Generated by Django 5.1 on 2024-08-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('agency_name', models.CharField(max_length=256)),
                ('student_name', models.CharField(max_length=256)),
                ('Mobilenumber', models.CharField(max_length=50)),
                ('university', models.CharField(blank=True, max_length=256)),
                ('submitting_for', models.CharField(blank=True, max_length=256)),
                ('tacking_no', models.CharField(max_length=25)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(max_length=256)),
            ],
        ),
    ]
