# Generated by Django 5.1 on 2024-08-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_agency_mobilenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='number_doc',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='opened_doc',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
