# Generated by Django 5.1 on 2024-08-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_agency_number_doc_alter_agency_opened_doc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=256)),
                ('number_doc', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
