# Generated by Django 5.1 on 2024-08-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Totalcount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_doc', models.CharField(default=0, max_length=256)),
                ('opened_doc', models.CharField(default=0, max_length=256)),
                ('closed_doc', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
