# Generated by Django 5.1 on 2024-08-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_totalcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalcount',
            name='opened_doc',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='totalcount',
            name='total_doc',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
