# Generated by Django 5.1 on 2024-08-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_totalcount_opened_doc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalcount',
            name='agency',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
