# Generated by Django 5.1 on 2024-08-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_document_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalcount',
            name='processing',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
