# Generated by Django 5.1 on 2024-08-17 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_totalcount_processing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totalcount',
            name='agency',
        ),
    ]
