# Generated by Django 5.1 on 2024-08-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_remove_totalcount_agency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='tacking_no',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
