# Generated by Django 5.1 on 2024-08-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_alter_document_tacking_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='country',
        ),
        migrations.AddField(
            model_name='country',
            name='country',
            field=models.ManyToManyField(to='dashboard.document'),
        ),
    ]
