# Generated by Django 5.1 on 2024-08-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_remove_country_country_country_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='country',
        ),
        migrations.AddField(
            model_name='country',
            name='country',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
