# Generated by Django 5.1 on 2024-08-24 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_remove_country_country_country_country'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='agency_name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.CreateModel(
            name='userprofile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employeeid', models.PositiveIntegerField()),
                ('mobile_number', models.CharField(blank=True, max_length=80, verbose_name='Mobile number')),
                ('email', models.CharField(blank=True, max_length=256, verbose_name='email id')),
                ('role', models.CharField(blank=True, max_length=25)),
                ('location', models.CharField(blank=True, max_length=64)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
