# Generated by Django 5.1 on 2024-08-24 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_alter_agency_agency_name_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agency',
            old_name='number_doc',
            new_name='total_doc',
        ),
    ]
