# Generated by Django 5.1 on 2024-08-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_rename_number_doc_agency_total_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='agency_name',
            field=models.CharField(max_length=256),
        ),
    ]
