# Generated by Django 5.1 on 2024-08-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_alter_agency_agency_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='group',
            field=models.CharField(default=1, max_length=24),
            preserve_default=False,
        ),
    ]
