# Generated by Django 5.1 on 2024-11-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_document_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='updated_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
