# Generated by Django 5.1 on 2024-12-03 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_alter_agency_created_date_alter_agency_updated_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoicedetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('billing_to', models.CharField(max_length=125)),
                ('billing_from', models.CharField(default='Arriba international,malappuram', max_length=64)),
                ('description', models.CharField(max_length=125)),
                ('quantity', models.PositiveBigIntegerField(default=1)),
                ('billing_date', models.DateTimeField(auto_now_add=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True, null=True)),
                ('Document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.document')),
            ],
        ),
    ]
