# Generated by Django 5.1 on 2024-12-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_invoicedetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedetails',
            name='price',
            field=models.CharField(default=0, max_length=24),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoicedetails',
            name='total',
            field=models.CharField(default=0, max_length=24),
            preserve_default=False,
        ),
    ]
