# Generated by Django 5.1 on 2024-12-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_invoicedetails_price_invoicedetails_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicedetails',
            name='total',
        ),
        migrations.AddField(
            model_name='invoicedetails',
            name='payment_status',
            field=models.CharField(default='not paid', max_length=24),
        ),
    ]
