# Generated by Django 5.1 on 2024-12-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_remove_invoicedetails_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='Documentno',
            field=models.CharField(default=0, max_length=24),
        ),
    ]
