# Generated by Django 5.1 on 2024-12-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_document_documentno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedetails',
            name='payment_status',
            field=models.BooleanField(default='false'),
        ),
    ]
