# Generated by Django 5.1 on 2024-12-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_alter_invoicedetails_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedetails',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
