# Generated by Django 5.1 on 2024-12-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_alter_invoicedetails_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedetails',
            name='invoice_number',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
