# Generated by Django 5.1 on 2024-12-14 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_invoicedetails_invoice_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicedetails',
            old_name='Document',
            new_name='document',
        ),
    ]
