# Generated by Django 5.1 on 2024-12-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_rename_document_invoicedetails_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedetails',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
