# Generated by Django 5.1 on 2024-12-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_alter_invoicedetails_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedetails',
            name='invoice_number',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
