# Generated by Django 5.1 on 2024-12-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_alter_invoicedetails_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedetails',
            name='invoice_number',
            field=models.CharField(max_length=8),
        ),
    ]
