# Generated by Django 5.1 on 2024-12-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_alter_invoicedetails_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='pay_status',
            field=models.BooleanField(default=False),
        ),
    ]
