# Generated by Django 5.1 on 2024-12-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_document_pay_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedetails',
            name='balance_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoicedetails',
            name='paid_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
