# Generated by Django 5.1 on 2024-12-15 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_invoicedetails_balance_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicedetails',
            old_name='balance_amount',
            new_name='balance',
        ),
        migrations.RenameField(
            model_name='invoicedetails',
            old_name='paid_amount',
            new_name='paid',
        ),
    ]
