# Generated by Django 5.1 on 2024-12-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_rename_balance_amount_invoicedetails_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedetails',
            name='paid',
            field=models.IntegerField(default=0),
        ),
    ]
