# Generated by Django 5.1 on 2024-12-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_alter_invoicedetails_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedetails',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
