# Generated by Django 5.1 on 2024-12-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_alter_invoicedetails_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedetails',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
