# Generated by Django 5.1 on 2025-01-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_invoicedetails_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='number_doc',
            new_name='opened_doc',
        ),
        migrations.AddField(
            model_name='country',
            name='total_doc',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
