# Generated by Django 5.1 on 2025-01-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_rename_number_doc_country_opened_doc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
