# Generated by Django 5.1 on 2025-01-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0041_agency_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedetails',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'paid'), ('pending', 'pending')], default='pending', max_length=20),
        ),
    ]
