# Generated by Django 5.1 on 2025-01-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0042_alter_invoicedetails_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='pay_status',
            field=models.CharField(blank=True, default='pending', max_length=25),
        ),
    ]
